DefaultContentLanguage = "en"
baseURL = 'https://jodros.github.io/'
theme = 'minimal'
relativeURLs = true

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = "content/"
    title = 'Public Notebook'
    weight = 1

  [languages.fr]
    languageName = 'Français'
    contentDir = "content/fr"
    title = "Cahier public"
    weight = 2

  [languages.ru]
    languageName = 'Russian'
    contentDir = "content/ru"
    title = "Открытая тетрадь"
    weight = 3
     
  [languages.pt]
    languageName = 'Portuguese'
    contentDir = "content/pt"
    title = "Caderno público"
    weight = 4
    
[markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'colorful'
    tabWidth = 4

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1
